### ISSUE TITLE
Warning: htmlspecialchars() expects parameter 1 to be string, array given  in lib/Varien/Data/Form/Element/Abstract.php on line 151

### ISSUE THREAD

**Issue by erfanimani** [ebizmarts/magemonkey#27]
I'm getting this warning on the latest version from Magento Connect (1.1.21 and 1.1.22).

````
Warning: htmlspecialchars() expects parameter 1 to be string, array given  in /home/erfan/sites/mywebsite/lib/Varien/Data/Form/Element/Abstract.php on line 151

#0 [internal function]: mageCoreErrorHandler(2, 'htmlspecialchar...', '/home/erfan/sit...', 151, Array)
#1 /home/erfan/sites/mywebsite/lib/Varien/Data/Form/Element/Abstract.php(151): htmlspecialchars(Array, 2)
#2 /home/erfan/sites/mywebsite/lib/Varien/Data/Form/Element/Abstract.php(161): Varien_Data_Form_Element_Abstract->_escape(Array)
#3 /home/erfan/sites/mywebsite/lib/Varien/Data/Form/Element/Abstract.php(178): Varien_Data_Form_Element_Abstract->getEscapedValue()
#4 /home/erfan/sites/mywebsite/app/code/community/Ebizmarts/MageMonkey/Block/Lists.php(354): Varien_Data_Form_Element_Abstract->getElementHtml()
#5 /home/erfan/sites/mywebsite/app/design/frontend/base/default/template/magemonkey/lists.phtml(28): Ebizmarts_MageMonkey_Block_Lists->renderGroup(Array, Array)
#6 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(241): include('/home/erfan/sit...')
#7 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#8 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#9 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#10 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#11 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('magemonkey_addi...', true)
#12 /home/erfan/sites/mywebsite/app/code/core/Mage/Page/Block/Html/Wrapper.php(52): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#13 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Page_Block_Html_Wrapper->_toHtml()
#14 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#15 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#16 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#17 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#18 /home/erfan/sites/mywebsite/app/design/frontend/mywebsite/default/template/page/2columns-left.phtml(23): Mage_Core_Block_Abstract->getChildHtml('content')
#19 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(241): include('/home/erfan/sit...')
#20 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/mywebsite/d...')
#21 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#22 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#23 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#24 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#25 /home/erfan/sites/mywebsite/app/code/community/Ebizmarts/MageMonkey/controllers/Customer/AccountController.php(52): Mage_Core_Controller_Varien_Action->renderLayout()
#26 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Ebizmarts_MageMonkey_Customer_AccountController->indexAction()
#27 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#28 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#29 /home/erfan/sites/mywebsite/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#30 /home/erfan/sites/mywebsite/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#31 /home/erfan/sites/mywebsite/index.php(87): Mage::run('', 'store')
#32 {main}
````

**Comment by cbepxpa3ym** [comment]
This still happens in 1.2.1
Please, fix it!

**Comment by cbepxpa3ym** [comment]
What I see in logs is:

Warning: htmlspecialchars() expects parameter 1 to be string, array given  in html/lib/Varien/Data/Form/Element/Abstract.php on line 151

It is printed 2 times after I go to Newsletter Subscription section of My Account.

**Comment by gonzaloebiz** [comment]
Fixed for the next version, or you can download the file https://github.com/ebizmarts/magemonkey/blob/master/app/code/community/Ebizmarts/MageMonkey/Block/Lists.php

**Comment by cbepxpa3ym** [comment]
Thanks! 
But it is strange.. as this is the same 1.2.1 version. But code is different. All this confuses.

**Comment by gonzaloebiz** [comment]
The version if not released yet

**Comment by cbepxpa3ym** [comment]
The new problem I got now:

Notice: Undefined offset: 1  in html/app/code/community/Ebizmarts/MageMonkey/Helper/Data.php on line 698 

This happens at login.

**Comment by cbepxpa3ym** [comment]
What I did is replaced that file - Lists.php
