### ISSUE TITLE
unserialize() error when accessing configuration page in Admin Panel

### ISSUE THREAD

**Issue by mobweb** [ebizmarts/magemonkey#69]
Using Magento CE 1.9.0.1 and the latest version pulled from Github, I get the following notice when accessing the configuration page of MageMonkey in the Magento Admin Panel:

```
Notice: unserialize(): Error at offset 0 of 1022 bytes  in app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php on line 33

#0 [internal function]: mageCoreErrorHandler(8, 'unserialize(): ...', '/Users/louis/Dr...', 33, Array)
#1 app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php(33): unserialize('?              ...')
#2 app/code/core/Mage/Core/Model/Config/Data.php(78): Mage_Adminhtml_Model_System_Config_Backend_Serialized->_afterLoad()
#3 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(334): Mage_Core_Model_Config_Data->afterLoad()
#4 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#9 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 index.php(93): Mage::run('', 'store')
#14 {main}
```

**Comment by centerax** [comment]
Thanks for reporting this @mobweb , we will fix this ASAP.

**Comment by Santiagoebizmarts** [comment]
@mobweb Thanks for helping us noticing this. We just released a new version that solved this issue.
We did some changes to the code format and some xml files went wrong.
You can see the commit https://github.com/ebizmarts/magemonkey/commit/f8e4e2853dea7a1beeb32b7c69a0b8271cd928c9.

You can install MageMonkey now as ususal.

**Comment by mobweb** [comment]
Works perfectly now, thanks!
